version: '3.7'
services:
  app:
    container_name: onlineplant-nursery
    image: roshini111/onlineplant-nursery:0.0.1
    ports:
      - 9001:9001
    depends_on:
      - postgresqldb
    links:
      - postgresqldb:postgres
  postgresqldb:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      
    