apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlineplant-nursery
  namespace: default
spec:
  selector:
    matchLabels:
      app: onlineplant-nursery
  replicas: 1
  template:
    metadata:
      name: onlineplant-nursery
      labels:
        app: onlineplant-nursery
    spec:
      containers:
      - name: onlineplant-nursery
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                 name: postgres-secrets
                 key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                 name: postgres-secrets
                 key: password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: hostname-config
                key: postgres_host
        image: roshini111/onlineplant-nursery